Sub main_procedure()
    Dim Start_Timer As Single
        Start_Timer = start_execution_timer()
        TotalTime = finish_execution_timer(Start_Timer)
End Sub

Function start_execution_timer() As Single
    start_execution_timer = Timer
End Function

Function finish_execution_timer(Start_Timer) As Integer
    Dim Finish, TotalTime
    Finish = Timer
    
    TotalTime = Finish - Start_Timer
    finish_execution_timer = TotalTime
End Function
